### PR TITLE
feat: Update display classes to handle busy output and clear busy output.

### LINKED ISSUE #134: Busy spinner on LCD1602 display
Implement a busy spinner animation on the LCD1602 display when SMIBHID busy starting up or updating state etc.
Method to set and unset and argument for placement (row and column)

### PR DESCRIPTION
**Pull request by sjefferson99**
This closes #134

### CODE REVIEW

**Review by samcorky — APPROVED** [review]
Indenting looks off, might just be my mobile view!

**Comment by sjefferson99** [comment]
> Indenting looks off, might just be my mobile view!

@sam57719 The indenting is off on github copy, but fine local, will fiddle with it and get it right.

**Comment by sjefferson99** [comment]
> > Indenting looks off, might just be my mobile view!
> 
> @sam57719 The indenting is off on github copy, but fine local, will fiddle with it and get it right.

@sam57719 Fixed, but to do so it now renders the whole file as changed, but the change for this PR is shown in the earlier commit I haven't squashed, so this should be good to approve now?

**Review by samcorky — APPROVED** [review]
Looks great! 🤑🫡

**Review by samcorky — APPROVED** [review]

**Pull request merged**
